[package]
name = "polinomial_optics"
version = "0.1.0"
authors = ["luksab <lukas@sabatschus.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.6.1"
num = "0.4.0"
