[package]
name = "wgpu_test"
version = "0.1.0"
authors = ["luksab <lukas@sabatschus.de>"]
edition = "2018"
resolver = "2"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.10"
rayon = "1.4"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
anyhow = "1.0"
tobj = "3.0"
imgui = "0.8"
imgui-winit-support = "0.8"
imgui-wgpu = "0.17.1"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }
