[package]
name = "wgpu_test"
version = "0.1.0"
authors = ["luksab <lukas@sabatschus.de>"]
edition = "2018"
resolver = "2"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.10"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
